name = "Advent2019"
uuid = "92c28108-5d60-4230-9582-c610657999b9"
authors = ["Randall Boyes <33524191+rdboyes@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
